import type { Metadata } from "next";
import "./globals.css";
import { AppContextProvider } from "@/context";
import { Poppins, Inter } from "next/font/google";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Image Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${poppins.variable} font-sans bg-gradient-to-br from-blue-50 to-purple-50 dark:from-gray-900 dark:to-gray-800`}
      >
        <Image
          src="/inkly logo.png"
          alt="Image Generator Logo"
          width={160}
          height={40}
          className="mx-auto mb-6 w-40 my-4 dark:invert"
        />
        <AppContextProvider>{children}</AppContextProvider>
      </body>
    </html>
  );
}
