import type { Metadata } from "next";
import "./globals.css";
import { AppContextProvider } from "@/context";

export const metadata: Metadata = {
  title: "Image Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-sans`}>
        <AppContextProvider>{children}</AppContextProvider>
      </body>
    </html>
  );
}
